# Generated by Django 6.0.7 on 2026-08-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment_payment_amount_non_negative'),
        ('core', '0010_company_membership_and_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('moyasar', 'Moyasar')], max_length=20)),
                ('provider_event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='core.company')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_events', to='billing.payment')),
            ],
            options={
                'db_table': 'payment_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEventProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('deferred', 'Deferred'), ('failed', 'Failed')], default='received', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing', to='billing.paymentevent')),
            ],
            options={
                'db_table': 'payment_event_processing',
            },
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['payment', 'created_at'], name='payment_eve_payment_4bfa6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='payment_event_provider_event_unique'),
        ),
        migrations.AddIndex(
            model_name='paymenteventprocessing',
            index=models.Index(fields=['status', 'updated_at'], name='payment_eve_status_ea73e9_idx'),
        ),
    ]
