# Generated by Django 6.0.6 on 2026-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('self_assessment', 'Self Assessment'), ('ai_assessment', 'AI Assessment'), ('formal_audit', 'Formal Audit')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('ai_complete', 'AI Review Complete'), ('auditor_review', 'Auditor Review'), ('completed', 'Completed'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('overall_score', models.FloatField(default=0.0)),
                ('nca_score', models.FloatField(default=0.0)),
                ('aramco_score', models.FloatField(default=0.0)),
                ('sabic_score', models.FloatField(default=0.0)),
                ('total_controls', models.IntegerField(default=0)),
                ('compliant_controls', models.IntegerField(default=0)),
                ('non_compliant_controls', models.IntegerField(default=0)),
                ('partially_compliant_controls', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_summary_ar', models.TextField(blank=True)),
                ('auditor_report', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assessments',
            },
        ),
        migrations.CreateModel(
            name='CompanyControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('evidence_uploaded', 'Evidence Uploaded'), ('ai_reviewed', 'AI Reviewed'), ('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partially_compliant', 'Partially Compliant'), ('not_applicable', 'Not Applicable')], default='not_started', max_length=25)),
                ('ai_verdict', models.CharField(blank=True, max_length=25)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('ai_reasoning_ar', models.TextField(blank=True)),
                ('ai_recommendations', models.TextField(blank=True)),
                ('ai_recommendations_ar', models.TextField(blank=True)),
                ('auditor_verdict', models.CharField(blank=True, max_length=25)),
                ('auditor_notes', models.TextField(blank=True)),
                ('last_assessed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_controls',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('title_ar', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('evidence_type', models.CharField(choices=[('policy', 'Policy Document'), ('procedure', 'Procedure Document'), ('screenshot', 'System Screenshot'), ('config', 'Configuration Export'), ('report', 'Audit/Scan Report'), ('log', 'System Log'), ('interview', 'Interview Record'), ('certificate', 'Certificate/License'), ('other', 'Other')], default='policy', max_length=20)),
                ('evidence_guidance', models.TextField(blank=True)),
                ('evidence_guidance_ar', models.TextField(blank=True)),
                ('applies_to_sectors', models.JSONField(blank=True, default=list)),
                ('applies_to_sizes', models.JSONField(blank=True, default=list)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'controls',
            },
        ),
        migrations.CreateModel(
            name='ControlMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(choices=[('equivalent', 'Equivalent'), ('partial', 'Partial'), ('related', 'Related')], default='equivalent', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'control_mappings',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'domains',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('file_size', models.IntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('ocr_language', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing (OCR)'), ('ai_analyzing', 'AI Analyzing'), ('reviewed', 'AI Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='uploaded', max_length=20)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('ai_verdict', models.CharField(blank=True, max_length=25)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('ai_reasoning_ar', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evidences',
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('total_controls', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'frameworks',
            },
        ),
    ]
