# Generated by Django 6.0.6 on 2026-06-08 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assigned_auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.company'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_controls', to='core.company'),
        ),
        migrations.AddField(
            model_name='control',
            name='mapped_controls',
            field=models.ManyToManyField(blank=True, to='compliance.control'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_controls', to='compliance.control'),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='source_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='compliance.control'),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='target_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_mappings', to='compliance.control'),
        ),
        migrations.AddField(
            model_name='control',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='compliance.domain'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='company_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='compliance.companycontrol'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='compliance.framework'),
        ),
        migrations.AddField(
            model_name='control',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='compliance.framework'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='frameworks',
            field=models.ManyToManyField(related_name='assessments', to='compliance.framework'),
        ),
        migrations.AlterUniqueTogether(
            name='companycontrol',
            unique_together={('company', 'control')},
        ),
        migrations.AlterUniqueTogether(
            name='controlmapping',
            unique_together={('source_control', 'target_control')},
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together={('framework', 'control_id')},
        ),
    ]
