# Generated by Django 6.0.6 on 2026-06-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('issuer', models.CharField(choices=[('NCA', 'National Cybersecurity Authority'), ('ARAMCO', 'Saudi Aramco'), ('SABIC', 'SABIC'), ('INTERNAL', 'Internal / CyberTrust KSA'), ('LEGACY', 'Legacy / Bootstrap')], max_length=20)),
                ('document_type', models.CharField(choices=[('standard', 'Standard'), ('guideline', 'Guideline'), ('template', 'Template'), ('assessment_tool', 'Assessment Tool'), ('policy_template', 'Policy Template'), ('procedure_template', 'Procedure Template'), ('bootstrap_excel', 'Bootstrap Excel'), ('srs', 'SRS / System Document'), ('other', 'Other')], default='other', max_length=30)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_hash', models.CharField(blank=True, help_text='e.g. SHA-256', max_length=128, null=True)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('bilingual', 'Bilingual'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('is_current', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('draft', 'Draft'), ('legacy', 'Legacy'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'source_documents',
                'ordering': ['issuer', 'title', '-version'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('version_label', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('retired_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('draft', 'Draft'), ('legacy', 'Legacy')], default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='compliance.framework')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framework_versions', to='compliance.sourcedocument')),
            ],
            options={
                'db_table': 'framework_versions',
                'ordering': ['framework', 'code'],
            },
        ),
    ]
