# Generated by Django 5.2.17 on 2026-08-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_evidence_processing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued for Processing'), ('processing', 'Processing (OCR)'), ('ai_analyzing', 'AI Analyzing'), ('reviewed', 'AI Reviewed'), ('needs_manual_review', 'Needs Manual Review'), ('failed', 'Processing Failed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='uploaded', max_length=20),
        ),
    ]
