# Generated by Django 6.0.6 on 2026-06-09 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_sourcedocument_frameworkversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='external_reference',
            field=models.CharField(blank=True, help_text='e.g. NCA ECC 1-1-1, TPC-01, CT-01', max_length=100),
        ),
        migrations.AddField(
            model_name='control',
            name='framework_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='compliance.frameworkversion'),
        ),
        migrations.AddField(
            model_name='control',
            name='import_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='control',
            name='is_legacy_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='control',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='compliance.sourcedocument'),
        ),
        migrations.AddField(
            model_name='control',
            name='source_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='source_reference',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ControlVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(max_length=100)),
                ('control_id_snapshot', models.CharField(blank=True, max_length=50)),
                ('title_snapshot', models.CharField(blank=True, max_length=500)),
                ('statement_snapshot', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('retired_date', models.DateField(blank=True, null=True)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='compliance.control')),
                ('framework_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_versions', to='compliance.frameworkversion')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_versions', to='compliance.sourcedocument')),
            ],
            options={
                'db_table': 'control_versions',
                'ordering': ['control', '-effective_date', 'version_label'],
            },
        ),
        migrations.CreateModel(
            name='ControlApplicabilityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('official', 'Official'), ('inferred', 'Inferred'), ('legacy_excel', 'Legacy Excel')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicability_tags', to='compliance.control')),
            ],
            options={
                'db_table': 'control_applicability_tags',
                'ordering': ['control', 'tag'],
                'constraints': [models.UniqueConstraint(fields=('control', 'tag'), name='uniq_control_tag')],
            },
        ),
    ]
