# Generated by Django 6.0.6 on 2026-06-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_control_external_reference_control_framework_version_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='control',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(condition=models.Q(('framework_version__isnull', False)), fields=('framework_version', 'control_id'), name='uniq_official_control_per_framework_version'),
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(condition=models.Q(('framework_version__isnull', True)), fields=('framework', 'control_id'), name='uniq_legacy_control_per_framework'),
        ),
    ]
