# Generated by Django 6.0.6 on 2026-06-10 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_alter_control_unique_together_and_more'),
        ('core', '0003_user_email_verified_user_mfa_enabled_user_mfa_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIntakeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('is_government_entity', models.BooleanField(default=False)),
                ('is_critical_system_operator', models.BooleanField(default=False)),
                ('uses_cloud_services', models.BooleanField(default=False)),
                ('provides_cloud_services', models.BooleanField(default=False)),
                ('handles_sensitive_data', models.BooleanField(default=False)),
                ('handles_personal_data', models.BooleanField(default=False)),
                ('has_ot_environment', models.BooleanField(default=False)),
                ('has_remote_work', models.BooleanField(default=False)),
                ('manages_official_social_media_accounts', models.BooleanField(default=False)),
                ('works_with_aramco', models.BooleanField(default=False)),
                ('works_with_sabic', models.BooleanField(default=False)),
                ('aramco_supplier_type', models.CharField(blank=True, max_length=50)),
                ('sabic_supplier_type', models.CharField(blank=True, choices=[('NC', 'Network Connectivity'), ('CCS', 'Cloud Computing Services'), ('OMS', 'Outsourcing and Managed Services'), ('CS', 'Consultancy Services'), ('SM', 'Software Management'), ('OT', 'OT/ICS Products and Services')], max_length=10)),
                ('requested_frameworks', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake_profile', to='core.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_intake_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_intake_profiles',
            },
        ),
        migrations.CreateModel(
            name='FrameworkApplicabilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('applicable', 'Applicable'), ('not_applicable', 'Not Applicable'), ('needs_review', 'Needs Review'), ('manually_overridden', 'Manually Overridden')], max_length=25)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('rule', 'Rule Engine'), ('manual', 'Manual'), ('legacy_checkbox', 'Legacy Checkbox')], default='rule', max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicability_results', to='core.company')),
                ('framework_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicability_results', to='compliance.frameworkversion')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_applicability_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'framework_applicability_results',
                'ordering': ['company', 'framework_version'],
                'unique_together': {('company', 'framework_version')},
            },
        ),
    ]
