# Generated by Django 6.0.6 on 2026-06-10 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_companyintakeprofile_frameworkapplicabilityresult'),
        ('core', '0003_user_email_verified_user_mfa_enabled_user_mfa_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFrameworkScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], default='proposed', max_length=20)),
                ('source', models.CharField(choices=[('applicability_result', 'Applicability Result'), ('manual', 'Manual'), ('legacy_checkbox', 'Legacy Checkbox')], default='applicability_result', max_length=25)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicability_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scopes', to='compliance.frameworkapplicabilityresult')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scopes', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_scopes', to='core.company')),
                ('framework_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_scopes', to='compliance.frameworkversion')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_framework_scopes',
                'ordering': ['company', 'framework_version'],
                'unique_together': {('company', 'framework_version')},
            },
        ),
        migrations.CreateModel(
            name='ControlApplicabilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('applicable', 'Applicable'), ('not_applicable', 'Not Applicable'), ('needs_review', 'Needs Review'), ('manually_overridden', 'Manually Overridden')], default='applicable', max_length=25)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('framework_scope', 'Framework Scope'), ('rule', 'Rule'), ('manual', 'Manual')], default='framework_scope', max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_applicability', to='core.company')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicability_results', to='compliance.control')),
                ('framework_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_results', to='compliance.companyframeworkscope')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_control_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_applicability_results',
                'ordering': ['company', 'control'],
                'unique_together': {('company', 'control')},
            },
        ),
    ]
