# Generated by Django 6.0.6 on 2026-06-10 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_companyframeworkscope_controlapplicabilityresult'),
        ('core', '0003_user_email_verified_user_mfa_enabled_user_mfa_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('policy', 'Policy Document'), ('procedure', 'Procedure Document'), ('screenshot', 'System Screenshot'), ('config', 'Configuration Export'), ('report', 'Audit/Scan Report'), ('log', 'System Log'), ('interview', 'Interview Record'), ('certificate', 'Certificate/License'), ('other', 'Other')], default='policy', max_length=20)),
                ('requirement_level', models.CharField(choices=[('mandatory', 'Mandatory'), ('recommended', 'Recommended'), ('optional', 'Optional')], default='mandatory', max_length=20)),
                ('source', models.CharField(choices=[('default_template', 'Default Template'), ('official', 'Official Source'), ('manual', 'Manual')], default='default_template', max_length=20)),
                ('source_reference', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_requirements', to='compliance.control')),
            ],
            options={
                'db_table': 'evidence_requirements',
                'ordering': ['control', 'sort_order'],
                'unique_together': {('control', 'title')},
            },
        ),
        migrations.CreateModel(
            name='EvidenceChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('waived', 'Waived')], default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('waiver_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_checklist_items', to='core.company')),
                ('control_applicability_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='compliance.controlapplicabilityresult')),
                ('evidence_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='compliance.evidencerequirement')),
            ],
            options={
                'db_table': 'evidence_checklist_items',
                'ordering': ['company', 'control_applicability_result'],
                'unique_together': {('company', 'evidence_requirement')},
            },
        ),
    ]
