# Generated by Django 6.0.6 on 2026-06-10 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_evidencerequirement_evidencechecklistitem'),
        ('core', '0003_user_email_verified_user_mfa_enabled_user_mfa_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='evidence_v2/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 of the uploaded file', max_length=128)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('pending_review', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_reupload', 'Needs Re-upload'), ('archived', 'Archived')], default='pending_review', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='compliance.evidencechecklistitem')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_submissions', to='core.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence_submissions',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
