# Generated by Django 6.0.6 on 2026-06-10 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_evidencesubmission'),
        ('core', '0003_user_email_verified_user_mfa_enabled_user_mfa_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('needs_human_review', 'Needs Human Review')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_text_truncated', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('requirement_match', models.TextField(blank=True)),
                ('potential_gaps', models.TextField(blank=True)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=80)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('analysis_metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='compliance.evidencechecklistitem')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_analyses', to='core.company')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_analyses', to='compliance.control')),
                ('evidence_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='compliance.evidencerequirement')),
                ('evidence_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='compliance.evidencesubmission')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence_analysis_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
