# Generated by Django 6.0.6 on 2026-06-10 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_evidenceanalysisresult'),
        ('core', '0003_user_email_verified_user_mfa_enabled_user_mfa_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('compliant', 'Compliant'), ('partially_compliant', 'Partially Compliant'), ('non_compliant', 'Non-Compliant'), ('not_applicable', 'Not Applicable'), ('needs_more_evidence', 'Needs More Evidence')], default='not_reviewed', max_length=25)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('auditor_notes', models.TextField(blank=True)),
                ('remediation_required', models.BooleanField(default=False)),
                ('remediation_plan', models.TextField(blank=True)),
                ('remediation_due_date', models.DateField(blank=True, null=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('ai_summary_snapshot', models.TextField(blank=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('confidence_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_assessments', to='core.company')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='compliance.control')),
                ('control_applicability_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='compliance.controlapplicabilityresult')),
                ('framework_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='compliance.companyframeworkscope')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_assessments',
                'ordering': ['company', 'control'],
                'unique_together': {('company', 'control')},
            },
        ),
    ]
