# Generated by Django 6.0.6 on 2026-06-27 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_controlassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceTextExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('extracted', 'Extracted'), ('no_text_extracted', 'No Text Extracted'), ('unsupported_type', 'Unsupported Type'), ('too_large', 'Too Large'), ('failed', 'Failed')], max_length=32)),
                ('extracted_text', models.TextField(blank=True)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extraction_method', models.CharField(blank=True, max_length=64)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('truncated', models.BooleanField(default=False)),
                ('extracted_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_extraction', to='compliance.evidencesubmission')),
            ],
            options={
                'db_table': 'evidence_text_extractions',
            },
        ),
    ]
