# Generated by Django 6.0.6 on 2026-06-27 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0012_evidencetextextraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=32)),
                ('relevance', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unclear', 'Unclear')], max_length=32)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('matched_signals', models.JSONField(blank=True, default=list)),
                ('missing_items', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='compliance.evidencesubmission')),
            ],
            options={
                'db_table': 'evidence_ai_analyses',
            },
        ),
    ]
