# Generated by Django 6.0.6 on 2026-06-27 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_evidenceaianalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRuleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=32)),
                ('suggested_status', models.CharField(blank=True, max_length=64)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('rationale', models.TextField(blank=True)),
                ('rule_signals', models.JSONField(blank=True, default=list)),
                ('missing_requirements', models.JSONField(blank=True, default=list)),
                ('framework_type', models.CharField(blank=True, max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule_evaluation', to='compliance.evidencesubmission')),
            ],
            options={
                'db_table': 'evidence_rule_evaluations',
            },
        ),
    ]
