# Generated by Django 6.0.6 on 2026-06-27 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0014_evidenceruleevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorFinalVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('final_c', 'Final Compliant'), ('final_pc', 'Final Partially Compliant'), ('final_nc', 'Final Non-Compliant'), ('final_na', 'Final Not Applicable'), ('final_compliance', 'Final Compliance'), ('final_noncompliance', 'Final Non-Compliance'), ('final_not_applicable', 'Final Not Applicable'), ('needs_more_evidence', 'Needs More Evidence')], max_length=64)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('rationale', models.TextField()),
                ('required_actions', models.JSONField(blank=True, default=list)),
                ('framework_type', models.CharField(blank=True, max_length=32)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditor_final_verdicts', to=settings.AUTH_USER_MODEL)),
                ('source_rule_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_verdicts', to='compliance.evidenceruleevaluation')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_final_verdict', to='compliance.evidencesubmission')),
            ],
            options={
                'db_table': 'auditor_final_verdicts',
            },
        ),
    ]
