# Generated by Django 6.0.6 on 2026-07-01 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0015_auditorfinalverdict'),
        ('core', '0005_emailotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlGapAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('partially_compliant', 'Partially Compliant'), ('missing', 'Missing'), ('not_applicable', 'Not Applicable'), ('needs_review', 'Needs Review')], default='needs_review', max_length=25)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('extracted_text_available_count', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('calculated_by', models.CharField(default='deterministic_v1', max_length=64)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_gap_assessments', to='core.company')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_assessments', to='compliance.control')),
                ('framework_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_gap_assessments', to='compliance.frameworkversion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_gap_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_gap_assessments',
                'ordering': ['company', 'control'],
                'unique_together': {('company', 'control')},
            },
        ),
    ]
