# Generated by Django 6.0.6 on 2026-07-16 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0016_controlgapassessment'),
        ('core', '0006_auditlog_audit_logs_company_2b43cb_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evidencesubmission',
            index=models.Index(fields=['company', '-uploaded_at'], name='evidence_su_company_1f23bc_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencesubmission',
            index=models.Index(fields=['company', 'status'], name='evidence_su_company_f9ccde_idx'),
        ),
    ]
