# Generated by Django 6.0.6 on 2026-07-23 12:31

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0017_evidencesubmission_evidence_su_company_1f23bc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(storage=core.storage.private_media_storage, upload_to='evidence/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='evidencesubmission',
            name='uploaded_file',
            field=models.FileField(storage=core.storage.private_media_storage, upload_to='evidence_v2/%Y/%m/'),
        ),
    ]
