# Generated by Django 6.0.6 on 2026-06-08 09:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('cr_number', models.CharField(max_length=20, unique=True, verbose_name='CR Number')),
                ('sector', models.CharField(choices=[('oil_gas', 'Oil & Gas'), ('petrochemical', 'Petrochemical'), ('banking', 'Banking & Finance'), ('telecom', 'Telecommunications'), ('healthcare', 'Healthcare'), ('government', 'Government'), ('defense', 'Defense'), ('energy', 'Energy & Utilities'), ('manufacturing', 'Manufacturing'), ('technology', 'Technology'), ('logistics', 'Logistics & Transport'), ('construction', 'Construction'), ('retail', 'Retail'), ('education', 'Education'), ('other', 'Other')], max_length=30)),
                ('size', models.CharField(choices=[('micro', 'Micro (1-9 employees)'), ('small', 'Small (10-49 employees)'), ('medium', 'Medium (50-249 employees)'), ('large', 'Large (250-999 employees)'), ('enterprise', 'Enterprise (1000+ employees)')], max_length=20)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('classified', 'Classified'), ('in_assessment', 'In Assessment'), ('audit_ready', 'Audit Ready'), ('certified', 'Certified'), ('expired', 'Certificate Expired')], default='registered', max_length=20)),
                ('target_aramco', models.BooleanField(default=False)),
                ('target_sabic', models.BooleanField(default=False)),
                ('target_nca', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('classification_date', models.DateTimeField(blank=True, null=True)),
                ('classification_summary', models.TextField(blank=True)),
                ('classification_summary_ar', models.TextField(blank=True)),
                ('overall_compliance_score', models.FloatField(default=0.0)),
                ('nca_score', models.FloatField(default=0.0)),
                ('aramco_score', models.FloatField(default=0.0)),
                ('sabic_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Platform Admin'), ('company_admin', 'Company Admin'), ('compliance_officer', 'Compliance Officer'), ('it_security', 'IT/Security Team'), ('bu_manager', 'Business Unit Manager'), ('executive', 'Executive'), ('auditor', 'Certified Auditor')], default='company_admin', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('preferred_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.company')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
