# Generated by Django 6.0.6 on 2026-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_email_verified_user_mfa_enabled_user_mfa_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, default='SA', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
