# Generated by Django 6.0.6 on 2026-07-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailotp'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', '-created_at'], name='audit_logs_company_2b43cb_idx'),
        ),
    ]
