# Generated by Django 6.0.6 on 2026-07-17 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditlog_audit_logs_company_2b43cb_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Platform Admin'), ('company_admin', 'Company Admin'), ('compliance_officer', 'Compliance Officer'), ('it_security', 'IT/Security Team'), ('bu_manager', 'Business Unit Manager'), ('executive', 'Executive'), ('auditor', 'Certified Auditor')], default='compliance_officer', max_length=20)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.company')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='user_invite_company_62dd51_idx')],
            },
        ),
    ]
