# Generated by Django 6.0.7 on 2026-08-16 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_memberships_and_journeys(apps, schema_editor):
    Company = apps.get_model('core', 'Company')
    User = apps.get_model('core', 'User')
    CompanyMembership = apps.get_model('core', 'CompanyMembership')
    CompanyJourney = apps.get_model('core', 'CompanyJourney')

    # Preserve every legacy User.company relationship as an explicit active
    # default membership. Bulk insert with ignore_conflicts makes this safe on
    # reruns and for databases restored from partially migrated backups.
    memberships = []
    for user in User.objects.exclude(company_id__isnull=True).iterator():
        memberships.append(CompanyMembership(
            user_id=user.id,
            company_id=user.company_id,
            role=user.role,
            is_active=True,
            is_default=True,
        ))
    CompanyMembership.objects.bulk_create(memberships, ignore_conflicts=True, batch_size=500)

    # Cyber-5 readiness work must not be labeled as an official certificate.
    Company.objects.filter(status='certified').update(status='review_ready')
    states = {
        'registered': 'registered',
        'classified': 'intake_in_progress',
        'in_assessment': 'under_internal_review',
        'audit_ready': 'review_ready',
        'review_ready': 'review_ready',
        'expired': 'review_closed',
    }
    journeys = [
        CompanyJourney(company_id=company.id, state=states.get(company.status, 'registered'))
        for company in Company.objects.all().only('id', 'status').iterator()
    ]
    CompanyJourney.objects.bulk_create(journeys, ignore_conflicts=True, batch_size=500)


def reverse_backfill(apps, schema_editor):
    # Do not delete historical membership/journey records on reverse migration.
    # Reversal only restores the choice list at schema level.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_mfa_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(
                choices=[
                    ('registered', 'Registered'),
                    ('classified', 'Classified'),
                    ('in_assessment', 'In Assessment'),
                    ('audit_ready', 'Audit Ready'),
                    ('review_ready', 'Ready for Internal Review'),
                    ('expired', 'Review Expired'),
                ],
                default='registered',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='CompanyJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('registered', 'Registered'), ('subscription_pending', 'Subscription Pending'), ('intake_in_progress', 'Intake In Progress'), ('scope_ready', 'Framework Scope Ready'), ('evidence_in_progress', 'Evidence In Progress'), ('review_ready', 'Ready for Internal Review'), ('under_internal_review', 'Under Internal Review'), ('review_closed', 'Internal Review Closed')], default='registered', max_length=32)),
                ('state_reason', models.CharField(blank=True, max_length=250)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='core.company')),
            ],
            options={
                'db_table': 'company_journeys',
                'indexes': [models.Index(fields=['state', 'updated_at'], name='company_jou_state_c8c20a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Platform Admin'), ('company_admin', 'Company Admin'), ('compliance_officer', 'Compliance Officer'), ('it_security', 'IT/Security Team'), ('bu_manager', 'Business Unit Manager'), ('executive', 'Executive'), ('auditor', 'Certified Auditor')], default='compliance_officer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_memberships',
                'indexes': [models.Index(fields=['company', 'is_active'], name='company_mem_company_81122f_idx')],
                'constraints': [
                    models.UniqueConstraint(fields=('user', 'company'), name='company_membership_unique'),
                    models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('user',), name='company_membership_one_active_default'),
                ],
            },
        ),
        migrations.RunPython(backfill_memberships_and_journeys, reverse_backfill),
    ]
