# Generated by Django 6.0.6 on 2026-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.IntegerField()),
                ('control_id', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('input_text', models.TextField(blank=True)),
                ('verdict', models.CharField(max_length=25)),
                ('confidence', models.FloatField(default=0.0)),
                ('reasoning', models.TextField(blank=True)),
                ('reasoning_ar', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('recommendations_ar', models.TextField(blank=True)),
                ('model_used', models.CharField(max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='AIClassificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('model_used', models.CharField(max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_classification_logs',
            },
        ),
        migrations.CreateModel(
            name='GapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_code', models.CharField(max_length=50)),
                ('total_controls', models.IntegerField(default=0)),
                ('compliant_count', models.IntegerField(default=0)),
                ('non_compliant_count', models.IntegerField(default=0)),
                ('partially_compliant_count', models.IntegerField(default=0)),
                ('not_assessed_count', models.IntegerField(default=0)),
                ('compliance_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('high_risk_gaps', models.JSONField(default=list)),
                ('remediation_priorities', models.JSONField(default=list)),
                ('ai_prediction', models.TextField(blank=True)),
                ('ai_prediction_ar', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gap_analyses',
            },
        ),
    ]
