# Generated by Django 6.0.6 on 2026-06-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiclassificationlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_logs', to='core.company'),
        ),
        migrations.AddField(
            model_name='gapanalysis',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_analyses', to='core.company'),
        ),
    ]
