# Generated by Django 6.0.6 on 2026-08-13 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_initial'),
        ('compliance', '0002_initial'),
        ('core', '0003_user_email_verified_user_mfa_enabled_user_mfa_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('credential_reference', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_model_profiles',
            },
        ),
        migrations.CreateModel(
            name='AIDecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_key', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(max_length=40)),
                ('policy_version_reference', models.CharField(blank=True, max_length=100)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('output_payload', models.JSONField(default=dict)),
                ('output_hash', models.CharField(db_index=True, max_length=64)),
                ('cited_chunk_indexes', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('review_required', 'Review required'), ('rejected', 'Rejected'), ('error', 'Error')], max_length=24)),
                ('human_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('trace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_decision_records', to='core.company')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_decision_records', to='compliance.control')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_records', to='compliance.evidence')),
                ('human_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_decisions', to=settings.AUTH_USER_MODEL)),
                ('model_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.modelprofile')),
            ],
            options={
                'db_table': 'ai_decision_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('version', models.CharField(max_length=40)),
                ('purpose', models.CharField(max_length=100)),
                ('template', models.TextField()),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_prompt_templates',
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='unique_ai_prompt_template_version')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='compliance.evidence')),
            ],
            options={
                'db_table': 'evidence_chunks',
                'ordering': ['chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('evidence', 'chunk_index'), name='unique_evidence_chunk_index')],
            },
        ),
    ]
