# Generated by Django 6.0.6 on 2026-08-13 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0002_initial'),
        ('core', '0003_user_email_verified_user_mfa_enabled_user_mfa_secret_and_more'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlStatusRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_status', models.CharField(max_length=25)),
                ('rule_reference', models.CharField(max_length=255)),
                ('rationale', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_recommendations', to='compliance.companycontrol')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_status_recommendations', to=settings.AUTH_USER_MODEL)),
                ('test_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_recommendation', to='integrations.controltestresult')),
            ],
            options={
                'db_table': 'control_status_recommendations',
            },
        ),
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('schema_version', models.CharField(default='1.0', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed'), ('dead_letter', 'Dead Letter')], default='pending', max_length=16)),
                ('available_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_events', to='core.company')),
            ],
            options={
                'db_table': 'domain_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('event_types', models.JSONField(default=list)),
                ('signing_secret_reference', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='core.company')),
            ],
            options={
                'db_table': 'webhook_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead_letter', 'Dead Letter')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='platform_events.domainevent')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='platform_events.webhooksubscription')),
            ],
            options={
                'db_table': 'webhook_deliveries',
            },
        ),
        migrations.AddConstraint(
            model_name='domainevent',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_domain_event_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='webhooksubscription',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_webhook_name'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'subscription'), name='unique_event_webhook_delivery'),
        ),
    ]
