# Generated by Django 6.0.6 on 2026-06-25 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0011_controlassessment'),
        ('core', '0004_company_country_company_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('control_assessment', 'Control Assessment'), ('evidence_analysis', 'Evidence Analysis'), ('gap_analysis', 'Gap Analysis'), ('auditor_finding', 'Auditor Finding')], default='manual', max_length=30)),
                ('category', models.CharField(choices=[('governance', 'Governance'), ('access_control', 'Access Control'), ('incident_response', 'Incident Response'), ('cloud_security', 'Cloud Security'), ('third_party', 'Third Party'), ('data_protection', 'Data Protection'), ('business_continuity', 'Business Continuity'), ('other', 'Other')], default='other', max_length=30)),
                ('likelihood', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('impact', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('inherent_score', models.PositiveSmallIntegerField(default=1)),
                ('residual_likelihood', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('residual_impact', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('residual_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='open', max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=160)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_items', to='core.company')),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_items', to='compliance.control')),
                ('control_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_items', to='compliance.controlassessment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to=settings.AUTH_USER_MODEL)),
                ('evidence_analysis_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_items', to='compliance.evidenceanalysisresult')),
                ('evidence_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_items', to='compliance.evidencesubmission')),
                ('framework_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_items', to='compliance.frameworkversion')),
            ],
            options={
                'db_table': 'risk_items',
                'ordering': ['-inherent_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemediationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner_name', models.CharField(blank=True, max_length=160)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_tasks', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_remediation_tasks', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='risk.riskitem')),
            ],
            options={
                'db_table': 'remediation_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
