# Generated by Django 6.0.6 on 2026-07-16 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0017_evidencesubmission_evidence_su_company_1f23bc_idx_and_more'),
        ('core', '0006_auditlog_audit_logs_company_2b43cb_idx'),
        ('risk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['company', 'status'], name='risk_items_company_9441ac_idx'),
        ),
    ]
