# Generated by Django 6.0.6 on 2026-06-24 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_company_country_company_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('license_or_membership_no', models.CharField(blank=True, max_length=120)),
                ('specialization', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='SA', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending_review', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditor_profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('scope', models.CharField(choices=[('reports_only', 'Reports Only'), ('evidence_review', 'Evidence Review'), ('full_review', 'Full Review')], default='reports_only', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_assignments', to='core.company')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_assignments', to=settings.AUTH_USER_MODEL)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='auditors.auditorprofile')),
            ],
            options={
                'db_table': 'auditor_assignments',
                'ordering': ['-requested_at'],
            },
        ),
    ]
