# Generated by Django 6.0.6 on 2026-07-01 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0001_initial'),
        ('core', '0005_emailotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCRMNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('visibility', models.CharField(default='internal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='core.company')),
            ],
            options={
                'db_table': 'company_crm_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCRMProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_status', models.CharField(choices=[('new', 'New'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('needs_follow_up', 'Needs follow-up'), ('blocked', 'Blocked'), ('inactive', 'Inactive')], default='new', max_length=20)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('internal_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_assigned_companies', to=settings.AUTH_USER_MODEL)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to='core.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_crm_profiles',
            },
        ),
    ]
