# Generated by Django 6.0.6 on 2026-07-09 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditors', '0002_companycrmnote_companycrmprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorassignment',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditorassignment',
            name='response_note',
            field=models.TextField(blank=True),
        ),
    ]
