# Generated by Django 6.0.6 on 2026-08-13 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0002_initial'),
        ('core', '0003_user_email_verified_user_mfa_enabled_user_mfa_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('auth_type', models.CharField(choices=[('oauth2', 'OAuth 2.0'), ('api_key', 'API Key'), ('service_account', 'Service Account'), ('manual', 'Manual Upload'), ('mock', 'Mock/Test Connector')], max_length=24)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integration_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ControlTestDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('schedule_minutes', models.PositiveIntegerField(default=1440)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_test_definitions', to='core.company')),
                ('controls', models.ManyToManyField(related_name='test_definitions', to='compliance.control')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_control_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_test_definitions',
                'ordering': ['company_id', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ControlTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('event', 'Event')], default='manual', max_length=16)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_test_runs', to='core.company')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='integrations.controltestdefinition')),
            ],
            options={
                'db_table': 'control_test_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled'), ('revoked', 'Revoked'), ('error', 'Error')], default='draft', max_length=16)),
                ('credential_reference', models.CharField(blank=True, max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_connections', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='integrations.integrationprovider')),
            ],
            options={
                'db_table': 'integration_connections',
                'ordering': ['company_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='controltestdefinition',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_definitions', to='integrations.integrationconnection'),
        ),
        migrations.CreateModel(
            name='ConnectorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('schema_version', models.CharField(default='1.0', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('dead_letter', 'Dead Letter')], default='received', max_length=16)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_events', to='core.company')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='integrations.integrationconnection')),
            ],
            options={
                'db_table': 'connector_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning'), ('error', 'Error')], max_length=16)),
                ('summary', models.TextField()),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('evidence_uri', models.CharField(blank=True, max_length=500)),
                ('evidence_hash', models.CharField(blank=True, max_length=64)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_results', to='compliance.control')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='integrations.controltestrun')),
            ],
            options={
                'db_table': 'control_test_results',
                'constraints': [models.UniqueConstraint(fields=('run', 'control'), name='unique_test_result_per_control')],
            },
        ),
        migrations.AddConstraint(
            model_name='controltestdefinition',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_company_control_test_key'),
        ),
        migrations.AddConstraint(
            model_name='connectorevent',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_connector_event_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(fields=('company', 'provider', 'name'), name='unique_company_provider_connection'),
        ),
    ]
