# Generated by Django 6.0.6 on 2026-06-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('drift', 'Configuration Drift'), ('access_change', 'Access Control Change'), ('score_drop', 'Score Drop'), ('certificate_expiry', 'Certificate Expiry'), ('new_vulnerability', 'New Vulnerability'), ('policy_change', 'Policy Change'), ('system', 'System Alert')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('title_ar', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('affected_control', models.CharField(blank=True, max_length=50)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.company')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_code', models.CharField(max_length=50)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('days_remaining', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.company')),
            ],
            options={
                'db_table': 'certificate_trackers',
            },
        ),
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('overall_score', models.FloatField(default=0.0)),
                ('nca_score', models.FloatField(default=0.0)),
                ('aramco_score', models.FloatField(default=0.0)),
                ('sabic_score', models.FloatField(default=0.0)),
                ('controls_compliant', models.IntegerField(default=0)),
                ('controls_total', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='core.company')),
            ],
            options={
                'db_table': 'compliance_scores',
                'ordering': ['-date'],
                'unique_together': {('company', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('report_data', models.JSONField(default=dict)),
                ('summary_en', models.TextField(blank=True)),
                ('summary_ar', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='core.company')),
            ],
            options={
                'db_table': 'monthly_reports',
                'ordering': ['-month'],
                'unique_together': {('company', 'month')},
            },
        ),
    ]
