# Generated by Django 6.0.6 on 2026-06-25 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_controlassessment'),
        ('core', '0004_company_country_company_description_and_more'),
        ('monitoring', '0001_initial'),
        ('risk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('check_type', models.CharField(choices=[('evidence_freshness', 'Evidence Freshness'), ('remediation_overdue', 'Remediation Overdue'), ('risk_review', 'Risk Review'), ('manual_review', 'Manual Review'), ('policy_review', 'Policy Review'), ('control_status_review', 'Control Status Review')], default='manual_review', max_length=30)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('needs_review', 'Needs Review'), ('not_run', 'Not Run')], default='not_run', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_checks', to='core.company')),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_checks', to='compliance.control')),
                ('control_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_checks', to='compliance.controlassessment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monitoring_checks', to=settings.AUTH_USER_MODEL)),
                ('framework_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_checks', to='compliance.frameworkversion')),
            ],
            options={
                'db_table': 'monitoring_checks',
                'ordering': ['next_run_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('needs_review', 'Needs Review'), ('error', 'Error')], default='needs_review', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('details', models.TextField(blank=True)),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_runs', to='core.company')),
                ('monitoring_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='monitoring.monitoringcheck')),
            ],
            options={
                'db_table': 'monitoring_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_findings', to='core.company')),
                ('related_remediation_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_findings', to='risk.remediationtask')),
                ('related_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_findings', to='risk.riskitem')),
                ('monitoring_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='monitoring.monitoringrun')),
            ],
            options={
                'db_table': 'monitoring_findings',
                'ordering': ['-created_at'],
            },
        ),
    ]
