# Generated by Django 6.0.6 on 2026-07-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailotp'),
        ('monitoring', '0002_monitoringcheck_monitoringrun_monitoringfinding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['company', '-created_at'], name='alert_company_created_idx'),
        ),
    ]
