# Generated by Django 6.0.6 on 2026-08-13 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0002_initial'),
        ('core', '0003_user_email_verified_user_mfa_enabled_user_mfa_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'canonical_controls',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PolicyPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_packs',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_reference', models.URLField(blank=True)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policy_versions', to=settings.AUTH_USER_MODEL)),
                ('policy_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policy_engine.policypack')),
            ],
            options={
                'db_table': 'policy_versions',
                'ordering': ['policy_pack__key', '-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(default=dict)),
                ('result_data', models.JSONField(default=dict)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('decision_hash', models.CharField(db_index=True, max_length=64)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_evaluations', to='core.company')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_evaluations', to=settings.AUTH_USER_MODEL)),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='policy_engine.policyversion')),
            ],
            options={
                'db_table': 'policy_evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlCoverageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('equivalent', 'Equivalent'), ('partial', 'Partial'), ('supports', 'Supports')], max_length=16)),
                ('coverage_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_control_mappings', to=settings.AUTH_USER_MODEL)),
                ('canonical_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='policy_engine.canonicalcontrol')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_mappings', to='compliance.control')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage_mappings', to='policy_engine.policyversion')),
            ],
            options={
                'db_table': 'control_coverage_mappings',
            },
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(fields=('policy_pack', 'version'), name='unique_policy_pack_version'),
        ),
        migrations.AddConstraint(
            model_name='controlcoveragemapping',
            constraint=models.UniqueConstraint(fields=('canonical_control', 'control', 'policy_version'), name='unique_canonical_control_mapping_version'),
        ),
    ]
