# Generated by Django 6.0.6 on 2026-06-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditor_portal', '0001_initial'),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditornote',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_notes', to='compliance.assessment'),
        ),
    ]
