# Generated by Django 6.0.6 on 2026-06-08 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditor_portal', '0002_initial'),
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditornote',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditornote',
            name='company_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_portal_notes', to='compliance.companycontrol'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='compliance.assessment'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='compliance.assessment'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='company_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='compliance.companycontrol'),
        ),
    ]
