# Generated by Django 6.0.6 on 2026-07-11 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor_portal', '0003_initial'),
        ('compliance', '0016_controlgapassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='closing_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('responded', 'Responded'), ('under_review', 'Under Review'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyRFIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfi_responses', to='compliance.evidence')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='auditor_portal.documentrequest')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfi_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_rfi_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditorControlVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('compliant', 'Compliant'), ('partially_compliant', 'Partially Compliant'), ('non_compliant', 'Non-Compliant'), ('needs_more_evidence', 'Needs More Evidence'), ('not_applicable', 'Not Applicable')], default='not_reviewed', max_length=25)),
                ('rationale', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('impact', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_verdicts', to='compliance.assessment')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_verdicts', to=settings.AUTH_USER_MODEL)),
                ('company_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_verdicts', to='compliance.companycontrol')),
            ],
            options={
                'db_table': 'auditor_control_verdicts',
                'unique_together': {('assessment', 'company_control')},
            },
        ),
    ]
