# Generated by Django 6.0.6 on 2026-07-16 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor_portal', '0004_documentrequest_closed_at_and_more'),
        ('compliance', '0016_controlgapassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorcontrolverdict',
            name='implementation_level',
            field=models.CharField(blank=True, choices=[('not_implemented', 'Not Implemented'), ('partially_implemented', 'Partially Implemented'), ('implemented', 'Implemented'), ('not_applicable', 'Not Applicable')], max_length=25),
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('major_nc', 'Major Non-Conformity'), ('minor_nc', 'Minor Non-Conformity'), ('observation', 'Observation'), ('ofi', 'Opportunity For Improvement')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_remediation', 'In Remediation'), ('reverify', 'Pending Re-verification'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='compliance.assessment')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_findings', to=settings.AUTH_USER_MODEL)),
                ('company_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='compliance.companycontrol')),
            ],
            options={
                'db_table': 'audit_findings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('owner', models.CharField(blank=True, max_length=160)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done (awaiting re-test)'), ('verified', 'Verified')], default='planned', max_length=20)),
                ('verification_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='auditor_portal.auditfinding')),
            ],
            options={
                'db_table': 'corrective_actions',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
