# Generated by Django 6.0.6 on 2026-07-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor_portal', '0006_companymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrfiresponse',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='rfi_responses/%Y/%m/'),
        ),
    ]
