# Generated by Django 6.0.6 on 2026-07-21 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor_portal', '0007_companyrfiresponse_attachment'),
        ('compliance', '0017_evidencesubmission_evidence_su_company_1f23bc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorControlVerdictHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
                ('implementation_level', models.CharField(blank=True, max_length=25)),
                ('impact', models.CharField(blank=True, max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdict_history', to='compliance.assessment')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verdict_history_entries', to=settings.AUTH_USER_MODEL)),
                ('company_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdict_history', to='compliance.companycontrol')),
            ],
            options={
                'db_table': 'auditor_control_verdict_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assessment', 'company_control'], name='auditor_con_assessm_0ed180_idx')],
            },
        ),
    ]
