# Generated by Django 6.0.6 on 2026-07-23 12:31

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor_portal', '0008_auditorcontrolverdicthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrfiresponse',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=core.storage.private_media_storage, upload_to='rfi_responses/%Y/%m/'),
        ),
    ]
