# Generated by Django 6.0.6 on 2026-07-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor_portal', '0009_alter_companyrfiresponse_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditreport',
            name='assessment_status_at_issue',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='evidence_snapshot',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='snapshot_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
