# Generated by Django 6.0.6 on 2026-07-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor_portal', '0010_auditreport_assessment_status_at_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditreport',
            name='company_id_at_issue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='scope_snapshot',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='summary',
            field=models.JSONField(default=dict),
        ),
    ]
